#!/usr/bin/env bash
# install.sh — Install dms_waypipe plugin and Hyprland window rules.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DMS_PLUGIN_DIR="$HOME/.config/DankMaterialShell/plugins/vm-launcher"
HYPR_PLUGIN_DIR="$HOME/.config/hypr/plugins/dms_waypipe"
HYPRLAND_LUA="$HOME/.config/hypr/hyprland.lua"
CONFIG_PATH="$HOME/.config/dms-waypipe/config.json"

echo "=== dms_waypipe install ==="

# 1. Build Go binary as 'dms-vm'
echo "[1/5] Building dms-vm binary..."
cd "$SCRIPT_DIR"
mkdir -p build
go build -o build/dms-vm .
echo "    Built: $SCRIPT_DIR/build/dms-vm"

# 2. Install binary to ~/.local/bin/dms-vm
INSTALL_BIN="$HOME/.local/bin/dms-vm"
mkdir -p "$HOME/.local/bin"
# Kill old running binary to avoid "text file busy" on overwrite
pkill -f "dms-vm" 2>/dev/null || true
sleep 0.2
cp "$SCRIPT_DIR/build/dms-vm" "$INSTALL_BIN"
chmod +x "$INSTALL_BIN"
echo "[2/5] Installed dms-vm binary to $INSTALL_BIN"

# 3. Copy DMS plugin
echo "[3/5] Copying DMS plugin..."
mkdir -p "$DMS_PLUGIN_DIR"
cp "$SCRIPT_DIR/VmLauncher.qml"         "$DMS_PLUGIN_DIR/"
cp "$SCRIPT_DIR/VmLauncherSettings.qml" "$DMS_PLUGIN_DIR/"
cp "$SCRIPT_DIR/plugin.json"            "$DMS_PLUGIN_DIR/"
echo "    -> $DMS_PLUGIN_DIR"

# 4. Setup Hyprland plugin
echo "[4/5] Setting up Hyprland window_rules plugin..."
mkdir -p "$HYPR_PLUGIN_DIR"
if [ ! -f "$HYPR_PLUGIN_DIR/init.lua" ]; then
    cat > "$HYPR_PLUGIN_DIR/init.lua" << 'INITHEOF'
-- auto-generated by dms_waypipe install
require("plugins.dms_waypipe.window_rules")
INITHEOF
fi

# Add require to hyprland.lua if not present
if [ -f "$HYPRLAND_LUA" ]; then
    if ! grep -q 'plugins.dms_waypipe' "$HYPRLAND_LUA"; then
        echo 'require("plugins.dms_waypipe")' >> "$HYPRLAND_LUA"
        echo "    Added require to $HYPRLAND_LUA"
    else
        echo "    require already present in $HYPRLAND_LUA"
    fi
else
    echo "    WARNING: $HYPRLAND_LUA not found; skipping hyprland.lua setup"
fi

# 5. Create default config if missing
echo "[5/5] Config..."
mkdir -p "$(dirname "$CONFIG_PATH")"
if [ ! -f "$CONFIG_PATH" ]; then
    cat > "$CONFIG_PATH" << 'CONFIGEOF'
{
  "vms": {}
}
CONFIGEOF
    echo "    Created default config: $CONFIG_PATH"
else
    echo "    Config already exists: $CONFIG_PATH"
fi

# Generate initial window_rules.lua
echo ""
echo "Generating window_rules.lua..."
RULES_FILE="$HYPR_PLUGIN_DIR/window_rules.lua"
if ! "$INSTALL_BIN" generate-rules --write "$RULES_FILE" "$CONFIG_PATH"; then
    echo "    NOTE: generate-rules failed; writing placeholder"
    cat > "$RULES_FILE" << 'RULeseof'
-- Placeholder: rules are generated by the settings UI
-- Run: dms-vm generate-rules --write <path> <config>
RULeseof
fi

echo ""
echo "=== Install complete ==="
echo "Restart Hyprland to activate window_rules plugin."
echo "The dms-vm CLI is now available at: $INSTALL_BIN"
