-- window_rules.lua: per-VM window border color rules
-- Auto-generated by dms_waypipe. Do not edit manually.

local M = {}

function M.setup(vms)
    for vmName, vm in pairs(vms) do
        local color = vm.color or "#ff7b54"
        hl.window_rule({
            name = "vm-" .. vmName,
            match = { initial_title = "^(.*VM:" .. vmName .. ".*)$" },
            border_color = color,
        })
    end
end

return M
